environment: platform_homolog_environment
### Project Settings
componentId: blog-demo-cluster
cluster_name: blog-demo-cluster
owner: group:default/admin
instance_type: t3.medium
volume_size: 30
keypair_name: platform_kp
### Network Settings
vpc_id: vpc-051721395ecf1f7aa
domain: vkpr.platform.vee.codes
hostedZoneId: Z08737613ML5F3HE67WJ3
subnet_id: subnet-04dda6147dd9410f1
### Ingress Settings
ingress_window: true
basic_auth: true
issuer_type: staging
email: platformss@vee.codes
### Terraform Backend Settings
terraformStateBucketName: veecode-homolog-terraform-state
terraformStateBucketRegion: us-east-1
infracost: false
### Publish Settings
host: github.com
destination: veecode-homolog/blog-demo-cluster
specPublish: ${{ parameters.specPublish | parseRepoUrl | pick('owner') }}/${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishRepo: ${{ parameters.specPublish | parseRepoUrl | pick('repo') }}
specPublishBranch: 
### Observability Settings
observability_window: true
## Cluster configuration 
cluster_obs_name: obs-central-apr
cluster_obs_domain: platform.vee.codes
cluster_obs_public_ip: 34.199.187.50