---
cluster_name: "blog-demo-cluster"
VPC_ID: "vpc-051721395ecf1f7aa"
SUBNET_ID: "subnet-04dda6147dd9410f1"
instance_type: "t3.medium"
keypair: "platform_kp"
volume_size: "30"
domain: vkpr.platform.vee.codes